### PR TITLE
Added to parse up to 4 satellites' information from a GSV sentence.

### PR DESCRIPTION
**Pull request by jsjeong**
I added some code to parse satellite information (PRN, elevation, azimuth, and SNR) up to 4 satellites from a GSV sentence.

### CODE REVIEW

**Review by jacketizer — APPROVED** [review]
Looks good 👍

**Comment by jacketizer** [comment]
I like the fact that this uses an array instead of hardcoded struct members for each satellite. Are you using this feature/sentence @igrr ?

**Comment by igrr** [comment]
Agree, using an array instead of individual names for each satellite makes consuming the results easier.

I'm not sure what is the policy for breaking API changes, given that there are no tagged releases yet, i guess there isn't any. So from that perspective changing the API is probably fine.

Looks like this will need a manual rebase to resolve conflicts, since the approach is different from the one implemented by @jhaws1982.
@jsjeong are you still able/interested in doing the rebase here? While we have @jacketizer's attention, there is a decent chance to get things merged :) https://github.com/jacketizer/libnmea/pull/34 would be nice to rebase merge as well — it is affecting the ESP32 port which I'm maintaining ([due to a newlib limitation](https://github.com/igrr/libnmea-esp32#known-issues)).

**Comment by jacketizer** [comment]
> 
> 
> Agree, using an array instead of individual names for each satellite makes consuming the results easier.
> 
> I'm not sure what is the policy for breaking API changes, given that there are no tagged releases yet, i guess there isn't any. So from that perspective changing the API is probably fine.
> 
> Looks like this will need a manual rebase to resolve conflicts, since the approach is different from the one implemented by @jhaws1982.
> @jsjeong are you still able/interested in doing the rebase here? While we have @jacketizer's attention, there is a decent chance to get things merged :) #34 would be nice to rebase and merge as well — it is affecting the ESP32 port which I'm maintaining ([due to a newlib limitation](https://github.com/igrr/libnmea-esp32#known-issues)).

I approved #34 but I haven't tested it.

Good thinking about backwards compatability 👍  You're right this change should be OK since the other satellite PR was merged some days ago and no new release has happened since then :-)

I can fix the manual merge if no one else is up for it 👍

**Review by jacketizer — APPROVED** [review]

**Pull request merged**
