### PR TITLE
parse_stdin example: add missing messages, add a test

### PR DESCRIPTION
**Pull request by igrr**
A few new parsers were added recently, but the `parse_stdin` example didn't handle them.
I've copied the output code for these messages from the `minimum` example.

Also added a test which runs parse_stdin on a sample file with NMEA messages and compares the output against the expected one.

If this approach is okay, I think the systests.c & systests.sh become a bit redundant. It is easier to keep just the `parse_stdin` example up to date, and perform the system tests using it, than to keep both `parse_stdin` and `systests.c` up to date. Please let me know how you feel about removing systests.{c,sh} in favour of this `parse_stdin`-based test.

This depends on #49 for the formatting changes.

### CODE REVIEW

**Comment by jacketizer** [comment]
Yes, I agree, let's remove the systests :-)

**Comment by igrr** [comment]
@jacketizer Thanks for taking a look! This is ready, I have moved all the messages from systests to parse_stdin example test, removed systests, and added a note to README about running these tests.

**Review by jacketizer — APPROVED** [review]

**Comment by igrr** [comment]
Thanks for the approval @jacketizer. JFYI, you'll still need to click the merge button — since I don't have write access to this repo, I can't merge this even if the PR is approved by you.

**Comment by jacketizer** [comment]
> 
> 
> Thanks for the approval @jacketizer. JFYI, you'll still need to click the merge button — since I don't have write access to this repo, I can't merge this even if the PR is approved by you.

Sorry, I forgot it :-D

**Comment by igrr** [comment]
Thanks for the merge and for granting me commit access!

**Pull request merged**
